import Head from "next/head";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import About from "../components/About";
import InfoArea from "../components/InfoArea";
import Footer from "../components/Footer";

export default function Home() {
  const [account, setAccount] = useState("connect");
  const [nftInfo, setNftInfo] = useState({});

  useEffect(() => {
    setAccount("0x746Dc9D8fdeCd183d3F5Dd33F2374c5C8E8173Ff");
    console.log(account);
    console.log(process.env.COVALENT_KEY);
  }, [account]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Courier+Prime:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Navbar setAccount={setAccount} />
      <main id={styles.maincontainer}>
        <About />
        <InfoArea nftInfo={nftInfo} />
      </main>
      <Footer />
    </div>
  );
}
